### PR TITLE
Add branch for 6.8

### PR DESCRIPTION
**Pull request by xduugu**
@grulja, could you please create a new branch for 6.8, as you have done for 5.15-24.08, so I can change the base branch to it?

### CODE REVIEW

**Comment by polter-rnd** [comment]
bot,build

**Comment by polter-rnd** [comment]
bot, build

**Comment by grulja** [comment]
`branch/6.8` created

**Comment by xduugu** [comment]
Thanks, @grulja. I've changed the base branch to `branch/6,8`.

**Pull request merged**
